project:
  type: website

website:
  title: "Yes! You can do that in `mgcv`!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contributing.qmd
      - text: Articles
        menu:
        - text: "GAM variance estimation"
          href: articles/gamvar.html
        - text: "Prediction intervals"
          href: articles/prediction_intervals.html
        - text: "Poisson processes in `mgcv`"
          href: articles/poisson_processes.html
        - text: "Neighbourhood cross-validation"
          href: articles/ncv.html
        - text: "Neighbourhood cross-validation for time series"
          href: articles/ncv_timeseries.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
