on:
  push:
    branches: main
permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

name: Render and Publish

# you need these permissions to publish to GitHub pages
# permissions: 
#     contents: write
#     pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: install gh cli
        run: |
          (type -p wget >/dev/null || (apt update && apt-get install wget -y)) \
          && mkdir -p -m 755 /etc/apt/keyrings \
          && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
          && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && mkdir -p -m 755 /etc/apt/sources.list.d \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && apt update \
          && apt install gh -y

      - name: setup quarto
        run: |
          gh --repo quarto-dev/quarto-cli release download --pattern '*-amd64.deb'
          dpkg -i $(ls quarto-*.deb)
          R -e 'install.packages(c("pak", "quarto"))'

      - name: install SSH
        run: apt install openssh-client -y

      - name: add github SSH key
        run: |
          mkdir ~/.ssh
          echo 'github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg= github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=' > ~/.ssh/known_hosts

      - name: install R packages
        run: |
          R -e 'install.packages(c(
                  "rmarkdown",
                  "ggplot2",
                  "dsm",
                  "Distance",
                  "fmesher",
                  "spatstat.data",
                  "lubridate",
                  "devtools",
                  "patchwork"
                ))'

      - name: pre-setup for quarto
        run: |
          quarto render
          quarto publish gh-pages --no-browser
#      - name: Publish to GitHub Pages (and render)
#        uses: quarto-dev/quarto-actions/publish@v2
#        with:
#          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions


